- .github/workflows/pull_request_title.yml
- .gitignore
- commitlint.config.js
- package-lock.json
- package.json
resolves #9 
Hi @JoshuaKGoldberg 👋🏾 , Does this look okay ?
> ✨ feat: add gitmoji + commitlint pull request title linter via gh action

- .github/workflows/pull_request_title.yml
> 🐛 fix: restrict pull request title linter to main branch prs

- .github/PULL_REQUEST_TEMPLATE.md
> 📝 feat: add pull request template

- .github/dependabot.yml
-   [x] Addresses an existing open issue: fixes #7 
-   [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypescript/projects/blob/main/CONTRIBUTING.md) were taken
Add dependabot config file. (dependabot.yml). I am not sure if dependabot starts working automatically after this config file is commited, or  you still have to enable it manually in github settings.. This is my first trying dependabot. @JoshuaKGoldberg
> ✨ feat: add dependabot config

- .github/workflows/pull_request_title.yml
-   [x] Addresses an existing open issue: fixes #24 
-   [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypescript/projects/blob/main/CONTRIBUTING.md) were taken
> :bug: fix: fix workflow failing for pr title containing brackets

- .github/dependabot.yml
-   [x] Addresses an existing open issue: fixes #32 
-   [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypescript/projects/blob/main/CONTRIBUTING.md) were taken
> :bug: fix: add commitlint type to dependabot prefix

- .github/PULL_REQUEST_TEMPLATE.md
-   [x] Addresses an existing open issue: fixes #27 
-   [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypescript/projects/blob/main/CONTRIBUTING.md) were taken
> :bug: fix: fix broken contributing.md link in pull request template

- .github/dependabot.yml
- .github/workflows/pull_request_title.yml
- Revert dependabot to use default naming standards/convention
- Ignore PRs from dependabot on pr title linting CI
> ✨ chore: ignore pr title linting on pull requests from dependabot

- .husky/pre-commit
- package-lock.json
- package.json
- format/prettify staged files on commit
> :sparkles: feat: prettier staged files on commit

- projects/interfaces/vacation-planning/01-cities/index.test.ts
- projects/interfaces/vacation-planning/02-restaurants/index.test.ts
Fixes up the solution code to use the right names and coordinates.
> 🐛 fix: vacation-planning project test issues

- projects/unions-and-literals/narrow-trails/jest.config.js
- projects/unions-and-literals/primitive-cooking/package.json
Two more failing projects, in preparation for #41
> 🐛 fix: two more project solutions

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/01-typo.yaml
- .github/ISSUE_TEMPLATE/02-bug.yaml
- .github/ISSUE_TEMPLATE/03-tooling.yaml
- .github/ISSUE_TEMPLATE/config.yml
Uses a strategy similar to typescript-eslint's.
> :technologist: chore: add issue forms

- .github/FUNDING.yml
Adds a funding button pointing to my GitHub. 💸
> 📝 docs: add .github/FUNDING.yml

- .github/CONTRIBUTING.md
- README.md
Adds a `.github/CONTRIBUTING.md` with some basic preliminary info.
> 📝 docs: add .github/CONTRIBUTING.md

- .all-contributorsrc
- README.md
- Adds readme badges for github actions, markdownlint, prettier and typescript.
> 📝 docs: add readme badges

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/01-typo.yaml
- .github/ISSUE_TEMPLATE/02-bug.yaml
- .github/ISSUE_TEMPLATE/03-tooling.yaml
- .github/ISSUE_TEMPLATE/config.yml
> 🐛 chore: fixed a few small typos in tooling templates

- projects/objects/various-lawyerings/01-aviary-classification/README.md
- projects/objects/various-lawyerings/01-aviary-classification/index.ts
- projects/objects/various-lawyerings/01-aviary-classification/solution.ts
- projects/objects/various-lawyerings/02-case-management/README.md
- projects/objects/various-lawyerings/02-case-management/index.ts
- projects/objects/various-lawyerings/02-case-management/solution.ts
- projects/objects/various-lawyerings/03-making-arguments/README.md
- projects/objects/various-lawyerings/03-making-arguments/index.ts
- projects/objects/various-lawyerings/03-making-arguments/solution.ts
- projects/objects/various-lawyerings/README.md
- projects/objects/various-lawyerings/_category_.json
- projects/objects/various-lawyerings/jest.config.js
- projects/objects/various-lawyerings/package.json
Fun fact: I'm in Philadelphia and got the idea for this from visit the actual Paddy's Pub that It's Always Sunny in Philadelphia is based on!
> ✨ feat: added Objects > Various Lawyerings appetizer project

- projects/objects/the-typer/README.md
- projects/objects/the-typer/_category_.json
- projects/objects/the-typer/package.json
- projects/objects/the-typer/src/index.ts
- projects/objects/the-typer/src/solution.ts
- projects/objects/various-lawyerings/03-making-arguments/index.ts
> ✨ feat: add Objects > The Typer entree project

- projects/functions/secret-secrets/_category_.json
- projects/functions/structural-kitchen/README.md
- projects/functions/structural-kitchen/_category_.json
- projects/functions/structural-kitchen/jest.config.js
- projects/functions/structural-kitchen/package.json
- projects/functions/structural-kitchen/src/index.test.ts
- projects/functions/structural-kitchen/src/index.ts
- projects/functions/structural-kitchen/src/solution.ts
Inspired by my Wikipedia binging _Iron Chef_, _Iron Chef America_, and _Hell's Kitchen_.
> ✨ feat: add Functions > Structural Kitchen entree project

- projects/interfaces/playlist-soundness/README.md
- projects/interfaces/playlist-soundness/_category_.json
- projects/interfaces/playlist-soundness/jest.config.js
- projects/interfaces/playlist-soundness/package.json
- projects/interfaces/playlist-soundness/src/index.test.ts
- projects/interfaces/playlist-soundness/src/index.ts
- projects/interfaces/playlist-soundness/src/solution.ts
> ✨ feat: add new Interfaces > playlist-soundness entree project

- projects/classes/classifying-creatures/01-polly-parrots-properties/README.md
- projects/classes/classifying-creatures/01-polly-parrots-properties/index.test.ts
- projects/classes/classifying-creatures/01-polly-parrots-properties/index.ts
- projects/classes/classifying-creatures/01-polly-parrots-properties/solution.ts
- projects/classes/classifying-creatures/02-dog-displays/README.md
- projects/classes/classifying-creatures/02-dog-displays/index.test.ts
- projects/classes/classifying-creatures/02-dog-displays/index.ts
- projects/classes/classifying-creatures/02-dog-displays/solution.ts
- projects/classes/classifying-creatures/03-hamster-helpers/README.md
- projects/classes/classifying-creatures/03-hamster-helpers/index.test.ts
- projects/classes/classifying-creatures/03-hamster-helpers/index.ts
- projects/classes/classifying-creatures/03-hamster-helpers/solution.ts
- projects/classes/classifying-creatures/README.md
- projects/classes/classifying-creatures/_category_.json
- projects/classes/classifying-creatures/jest.config.js
- projects/classes/classifying-creatures/package.json
- projects/interfaces/playlist-soundness/README.md
- projects/unions-and-literals/narrow-trails/src/index.test.ts
Cute.
Also touches up a couple related readmes.
> ✨ feat: add Classes project: Classifying Creatures

- projects/classes/horror-factory/README.md
- projects/type-modifiers/type-forces/01-fabulous-secret-powers/README.md
- projects/type-modifiers/type-forces/01-fabulous-secret-powers/characters.ts
- projects/type-modifiers/type-forces/01-fabulous-secret-powers/index.test.ts
- projects/type-modifiers/type-forces/01-fabulous-secret-powers/index.ts
- projects/type-modifiers/type-forces/01-fabulous-secret-powers/solution.ts
- projects/type-modifiers/type-forces/02-artifact-assertions/README.md
- projects/type-modifiers/type-forces/02-artifact-assertions/characters.ts
- projects/type-modifiers/type-forces/02-artifact-assertions/index.test.ts
- projects/type-modifiers/type-forces/02-artifact-assertions/index.ts
- projects/type-modifiers/type-forces/02-artifact-assertions/solution.ts
- projects/type-modifiers/type-forces/README.md
- projects/type-modifiers/type-forces/_category_.json
- projects/type-modifiers/type-forces/jest.config.js
- projects/type-modifiers/type-forces/package.json
> ✨ feat: add new Type Modifiers > Type Forces appetizer project

- projects/generics/treasure-hunter/README.md
- projects/generics/treasure-hunter/_category_.json
- projects/generics/treasure-hunter/jest.config.js
- projects/generics/treasure-hunter/package.json
- projects/generics/treasure-hunter/src/index.test.ts
- projects/generics/treasure-hunter/src/index.ts
- projects/generics/treasure-hunter/src/solution.ts
- projects/type-modifiers/type-force/_category_.json
I started off thinking Indiana Jones, but now want to be more generally around fun archeology/explorers...
> ✨ feat: add new Generics > Treasure Hunter entree project

- projects/declaration-files/global-travels/01-passport-declarations/README.md
- projects/declaration-files/global-travels/01-passport-declarations/index.ts
- projects/declaration-files/global-travels/01-passport-declarations/solution.ts
- projects/declaration-files/global-travels/02-unexpected-methods/README.md
- projects/declaration-files/global-travels/02-unexpected-methods/index.ts
- projects/declaration-files/global-travels/02-unexpected-methods/solution.ts
- projects/declaration-files/global-travels/README.md
- projects/declaration-files/global-travels/_category_.json
- projects/declaration-files/global-travels/package.json
I'm all excited for my Europe travel. 😄
> ✨ feat: add new Declaration Files > Global Travels appetizer project

- projects/declaration-files/type-illusions/README.md
- projects/declaration-files/type-illusions/_category_.json
- projects/declaration-files/type-illusions/package.json
- projects/declaration-files/type-illusions/src/index.solution.ts
- projects/declaration-files/type-illusions/src/index.ts
- projects/declaration-files/type-illusions/src/show.d.ts
- projects/declaration-files/type-illusions/src/show.solution.d.ts
I've been meaning to watch the last season of Arrested Development.
> ✨ feat: add new Declaration Files > Type Illusions entree project

- projects/using-ide-features/temporary-code/Person.solution.ts
- projects/using-ide-features/temporary-code/README.md
- projects/using-ide-features/temporary-code/criticizePerson.solution.ts
- projects/using-ide-features/temporary-code/index.solution.ts
- projects/using-ide-features/temporary-code/index.test.ts
- projects/using-ide-features/temporary-code/index.ts
Originally part of this section's appetizer project.
> ✨ feat: added new Using IDE Features > Temporary Code project

- projects/interfaces/playlist-soundness/_category_.json
- projects/interfaces/playlist-soundness/package.json
- projects/unions-and-literals/narrow-trails/README.md
- projects/unions-and-literals/narrow-trails/_category_.json
- projects/unions-and-literals/narrow-trails/package.json
- projects/unions-and-literals/narrow-trails/src/index.test.ts
- projects/unions-and-literals/narrow-trails/src/solution.ts
Fixes the solution to check `=== 0` as per the project description. I like it this way rather than `< 0` because it gives a roughly 37% chance of victory to be more strict.
While I'm in the area, also aligns the project name to be _The Narrow Trail_ (to better match with _[The Oregon Trail](https://en.wikipedia.org/wiki/The_Oregon_Trail_(series))_).
> 🐛 fix: (the-)narrow-trails counts

- projects/using-ide-features/typearium/02-species-collections/README.md
- projects/using-ide-features/typearium/README.md
Fills out the README with full sentences.
> 🐛 fix: fill out typearium description

- .github/workflows/files.yml
- .github/workflows/test.yml
- projects/type-operations/array-type-shenanigans/01-flat-filter/tsconfig.test.json
- projects/type-operations/array-type-shenanigans/02-reverse/tsconfig.test.json
- projects/type-operations/array-type-shenanigans/03-zip/tsconfig.test.json
- projects/type-operations/array-type-shenanigans/package.json
- projects/type-operations/template-literal-type-shenanigans/01-spongecase/tsconfig.test.json
- projects/type-operations/template-literal-type-shenanigans/02-word-replace/tsconfig.test.json
- projects/type-operations/template-literal-type-shenanigans/03-split-on/tsconfig.test.json
- projects/type-operations/template-literal-type-shenanigans/package.json
Adds one more `test.yml` to verify `npm run test` passes after copying solution files.
Marking as a `fix` because it does fix some TSConfigs.
> 🐛 fix: also npm run test on solutions

- .github/CONTRIBUTING.md
- .github/DEVELOPMENT.md
There's not much info to fill out here, I think. More can always be added if anybody asks.
> 📝 docs: fill out DEVELOPMENT.md

- projects/interfaces/vacation-planning/02-restaurants/index.test.ts
- scripts/copy-solutions.sh
Should fix the build... https://github.com/LearningTypeScript/projects/runs/7707717858?check_suite_focus=true
> 🐛 fix: also copy .js files in copy-solutions.sh

- projects/type-operations/template-literal-type-shenanigans/01-spongecase/README.md
Fixed a typo in the SpOnGeCaSe project
> Fixed Typo

- commitlint.config.js
- package-lock.json
- package.json
> chore: replace gitmoji with conventional commits

- projects/declaration-files/global-travels/02-unexpected-methods/index.ts
> fix: removed solution in index.ts for Global Travels step 2

- projects/classes/classifying-creatures/02-dog-displays/index.ts
- projects/classes/classifying-creatures/03-hamster-helpers/README.md
- projects/type-modifiers/modifiers-of-the-types/02-artifact-assertions/README.md
- projects/type-modifiers/type-force/README.md
Fixes a few small inconsistencies in docs / TS templates. Should be self-explanatory, but I'm happy to explain any that are unclear. 
Once I finish reading the book, I'll probably do a pass to ensure the comments at the top of each `index.ts` match what the README is asking for; I've just been filing these as I found them.
Also if I want to get in the "All Contributors" section (assuming I qualify), do I edit that file manually or go through a bot? `CONTRIBUTING.md` was unclear on that point. 
Thanks!
---
Separately, do you have a preferred avenue for typos in the text of the book itself? I found a small one but didn't see a place to fix it.
> :memo: docs: fix misc typos

- .github/CONTRIBUTING.md
Directly mentions the all-contributor flow in the docs.
> docs: mention Contributing all-contributors flow

- projects/classes/classifying-creatures/03-hamster-helpers/README.md
Follows up on #174 by fixing one more typo.
> fix: one more Hamster Helpers typo

- projects/arrays/analyzing-dna/03-deep-equality/README.md
- projects/arrays/analyzing-dna/03-deep-equality/index.ts
- projects/arrays/analyzing-dna/04-deep-differences/README.md
- projects/arrays/analyzing-dna/04-deep-differences/index.ts
- projects/classes/classifying-creatures/03-hamster-helpers/README.md
- projects/functions/structural-kitchen/src/index.ts
- projects/generics/treasure-hunter/README.md
- projects/interfaces/vacation-planning/02-restaurants/index.ts
- projects/interfaces/vacation-planning/03-landmarks/README.md
- projects/interfaces/vacation-planning/03-landmarks/index.ts
- projects/objects/various-lawyerings/01-aviary-classification/index.ts
Similar to my previous PRs, this shores up inconsistencies where: 
- the markdown header didn't match the filename / path
- the stub function name in `index.ts` didn't match what was asked for in the corresponding `README`
- misc typos
Let me know if anything's unclear!
> 📝 docs: fix typos, section names, and function names

- projects/from-javascript-to-typescript/the-typeinator/02-callbacks-to-async-await/original.js
* add missing character
Adding missing character so that when doing the exercise, we know what is the expected message in the related test.
> 📝 docs: add missing character in The Typeinator

- projects/syntax-extensions/typespeare/01-whats-in-a-namespace/README.md
- projects/syntax-extensions/typespeare/02-much-ado-about-enums/README.md
- projects/syntax-extensions/typespeare/03-typus-andronicus/README.md
- projects/type-operations/template-literal-type-shenanigans/02-word-replace/README.md
- projects/type-operations/template-literal-type-shenanigans/03-split-on/README.md
A couple of readmes reference test files that don't exist. Also, a part 2 readme used instructions from part 1, so I updated them.
---
_edit_: also fixed instructions in readmes that specified the wrong number of type parameters and/or listed the wrong number.
> docs: fix prompt and remove reference to tests that don't exist

- projects/unions-and-literals/the-narrow-trail/README.md
Even number makes Food available.
Quote:
```3-6, Resupply:
If no Available Resource value is set: set Available Resource to Food if the rolled number is even or Water if the rolled number is odd
```
> Fix game logic example

- projects/the-type-system/system-of-a-clown/02-clown-availability/solution.ts
> fix: corrected clown names in system-of-a-clown solution

- projects/functions/structural-kitchen/README.md
Just noticed a typo in the page.
> fix: typo in Structural Kitchen

- projects/interfaces/vacation-planning/03-landmarks/README.md
After submitting my previous issue & PR I read this in the template 
> If this report is for a small typo you're sure is a mistake,
> feel free to instead send a pull request directly.
So submitting a PR directly instead. 😄 
---
In the Project **Vacation Planning** the keys mentioned in the Steps are incorrect.
> Lighthouses: It was first lit in `<lit>` and is `<feet>` feet high.
`<feet>` should be `<height>`
> Rivers: It flows for `<length>` miles and is `<deep>` feet deep at its deepest.
`<deep>` should be `<depth>`
I also noticed some entries in `landmarks.json` do not have all the keys required for each landmark but I guess that OK as they do affect the passing of the tests.
> docs: fix missing steps in Vacation Planning project

- projects/type-operations/zod-lite/package.json
> fix: correct zod-lite/package.json name

- projects/the-type-system/system-of-a-clown/02-clown-availability/solution.ts
> fix: add ': string' to clown-availability's let lastClown

- projects/functions/structural-kitchen/src/index.test.ts
> fix: correct structural-kitchen test names
